index:
    path: /
    controller: App\Controller\IndexController::index
competence:
    path: /competence/{area}
    controller: App\Controller\IndexController::competence
    requirements:
        area: '\d+'
quiz:
    path: /quiz/{competence}
    controller: App\Controller\QuizController::index
    requirements:
        competence: '\d+'
question:
    path: /quiz/question/{competence}
    controller: App\Controller\QuizController::question
    requirements:
        competence: '\d+'
questionadd:
    path: /addquestion
    controller: App\Controller\IndexController::addQuestion

areaadd:
    path: /addarea
    controller: App\Controller\IndexController::addAreas

competenceadd:
    path: /addcompetence
    controller: App\Controller\IndexController::addCompetence
