index:
    path: /
    controller: App\Controller\IndexController::index
competence:
    path: /competence/{area}
    controller: App\Controller\IndexController::competence
    requirements:
        area: '\d+'
quiz:
    path: /quiz/{competence}
    controller: App\Controller\QuizController::index
    requirements:
        competence: '\d+'
question:
    path: /quiz/question
    controller: App\Controller\QuizController::question
import:
    path: /import
    controller: App\Controller\IndexController::import

summary:
    path: /quiz/summary
    controller: App\Controller\QuizController::summary
