index:
    path: /
    controller: App\Controller\IndexController::index
quiz:
    path: /quiz
    controller: App\Controller\QuizController::index
question:
    path: /quiz/question
    controller: App\Controller\QuizController::question
